/**
 * @packageDocumentation
 * @module utils
 */

// This is a placeholder file that will be replaced by the generated packed.ts during build
// The actual packed.ts is generated by util/pack.js

const map: Record<string, string> = {};
const names: Record<string, string> = {};

/**
 * Unpack color names
 * @returns Record of color names to RGB arrays
 */
export default function unpack(): Record<string, number[]> {
  // This is just a placeholder implementation
  // The actual implementation will be provided by the generated packed.js
  return {};
}
