name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm

      - name: install
        run: npm ci

      - name: lint
        run: npm run lint

      - name: build
        run: npm run build

      - name: test
        run: xvfb-run --auto-servernum npm test
